# Generated by Django 3.2.3 on 2021-05-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0006_auto_20210525_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condidature',
            name='college_name',
            field=models.TextField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='condidature',
            name='company_names',
            field=models.TextField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='condidature',
            name='degree',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='condidature',
            name='designation',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='condidature',
            name='mobile_number',
            field=models.TextField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='condidature',
            name='skills',
            field=models.TextField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='condidature',
            name='total_experience',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
