# Generated by Django 3.2.3 on 2021-05-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0007_auto_20210525_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='condidature',
            name='experience',
            field=models.TextField(default='0', null=True),
        ),
    ]
