# Generated by Django 3.2.3 on 2021-05-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0008_condidature_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='condidature',
            name='masqué',
            field=models.BooleanField(default=False),
        ),
    ]
