# Generated by Django 3.2.3 on 2021-05-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0009_condidature_masqué'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condidature',
            name='masqué',
        ),
        migrations.AddField(
            model_name='offre',
            name='masqué',
            field=models.BooleanField(default=False),
        ),
    ]
