# Generated by Django 3.2.4 on 2021-06-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0010_auto_20210526_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='masqué',
            new_name='masque',
        ),
    ]
